version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 891377126243.dkr.ecr.us-east-1.amazonaws.com
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=$(COMMIT_HASH:=latest)
  build:
    commands:
      - docker build -t pizzaria-backend .
      - docker tag pizzaria-backend:latest 891377126243.dkr.ecr.us-east-1.amazonaws.com/pizzaria-backend:$IMAGE_TAG
  post_build:
    commands:
      - docker push 891377126243.dkr.ecr.us-east-1.amazonaws.com/pizzaria-backend:latest