apiVersion: apps/v1
kind: Deployment
metadata:
  name: pizzaria-backend-deployment
spec:
  selector:
    matchLabels:
      app: pizzaria-backend
  template:
    metadata:
      labels:
        app: pizzaria-backend
    spec:
      containers:
        - name: pizzaria-backend
          image: 891377126243.dkr.ecr.us-east-1.amazonaws.com/pizzaria-backend:latest
          ports:
            - containerPort: 3000