apiVersion: apps/v1
kind: Deployment
metadata:
  name: pizzaria-backend
spec:
  selector:
    matchLabels:
      app: pizzaria-backend
  template:
    metadata:
      labels:
        app: pizzaria-backend
    spec:
      containers:
        - image: 891377126243.dkr.ecr.us-east-1.amazonaws.com/pizzaria-backend:latest
          name: pizzaria-backend
          ports:
            - containerPort: 3000
          env: 
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: my-secrets
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: my-secrets
                  key: DB_PORT
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: my-secrets
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-secrets
                  key: DB_PASSWORD
            - name: DB_ADMIN_EMAIL
              valueFrom:
                secretKeyRef:
                  name: my-secrets
                  key: DB_ADMIN_EMAIL
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: my-secrets
                  key: DB_DATABASE
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: my-secrets
                  key: JWT_SECRET
            - name: JWT_EXPIRATION
              valueFrom:
                secretKeyRef:
                  name: my-secrets
                  key: JWT_EXPIRATION
            
          
            
