apiVersion: apps/v1
kind: Deployment
metadata:
  name: pizzaria-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pizzaria-backend
  template:
    metadata:
      labels:
        app: pizzaria-backend
    spec:
      containers:
        - image: 891377126243.dkr.ecr.us-east-1.amazonaws.com/pizzaria-backend
          name: pizzaria-backend
          ports:
            - containerPort: 3000
          
            
          
            
